/**
 * Netlify Function: telegram-webhook
 *
 * POST /.netlify/functions/telegram-webhook
 * Called by Telegram itself (not this app's frontend) whenever a user
 * messages the bot — specifically /start <userId>, sent automatically when
 * someone opens the https://t.me/<bot>?start=<userId> deep link generated by
 * connectTelegram() (src/lib/telegram.js) from the Dashboard.
 *
 * This is the only function in this codebase that receives requests from a
 * third party rather than this app's own frontend, so it can't use the usual
 * "Authorization: Bearer <supabase_access_token>" pattern every other admin
 * function uses. Instead it validates Telegram's own recommended mechanism —
 * a secret token set via setWebhook, echoed back on every call as the
 * X-Telegram-Bot-Api-Secret-Token header.
 *
 * Required env vars (Netlify dashboard — no VITE_ prefix):
 *   SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 *   TELEGRAM_BOT_TOKEN
 *   TELEGRAM_WEBHOOK_SECRET
 *
 * One-time setup (not this function's job): after deploying, call
 *   https://api.telegram.org/bot<TOKEN>/setWebhook?url=<site>/.netlify/functions/telegram-webhook&secret_token=<SECRET>
 * exactly once so Telegram knows to call this URL.
 */

import { createClient } from '@supabase/supabase-js'
import { timingSafeEqual } from 'crypto'
import { sendTelegramMessage } from './lib/telegram.js'

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

function secretMatches(headerValue) {
  const expected = process.env.TELEGRAM_WEBHOOK_SECRET ?? ''
  if (!expected || !headerValue) return false
  const a = Buffer.from(headerValue)
  const b = Buffer.from(expected)
  // timingSafeEqual throws on mismatched lengths rather than returning false.
  if (a.length !== b.length) return false
  return timingSafeEqual(a, b)
}

export const handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method not allowed' }
  }

  if (!secretMatches(event.headers['x-telegram-bot-api-secret-token'])) {
    return { statusCode: 401, body: JSON.stringify({ error: 'Invalid secret token' }) }
  }

  const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
  )

  // Telegram retries aggressively on non-200 responses — every branch below
  // returns 200 once the secret-token check passes, and problems are logged
  // instead of surfaced as an HTTP failure back to Telegram's servers.
  try {
    const update  = JSON.parse(event.body ?? '{}')
    const message = update.message
    const text    = message?.text ?? ''

    if (!text.startsWith('/start')) {
      return { statusCode: 200, body: '' }
    }

    const chatId = message.chat?.id
    const userId = text.split(' ')[1]?.trim()

    if (!userId || !UUID_RE.test(userId)) {
      if (chatId) {
        await sendTelegramMessage(supabase, null, chatId,
          "That link looks invalid — try reconnecting from the Dashboard's notification section.")
      }
      return { statusCode: 200, body: '' }
    }

    const { data, error } = await supabase
      .from('users')
      .update({ telegram_chat_id: String(chatId) })
      .eq('id', userId)
      .select('id')
      .maybeSingle()

    if (error || !data) {
      console.error('[telegram-webhook] link failed for userId', userId, error?.message)
      await sendTelegramMessage(supabase, null, chatId,
        "That link looks invalid — try reconnecting from the Dashboard's notification section.")
      return { statusCode: 200, body: '' }
    }

    console.log(`[telegram-webhook] linked user ${userId} to chat ${chatId}`)
    await sendTelegramMessage(supabase, userId, chatId,
      "Connected! You'll now get DeFi Tanda alerts here.")

    return { statusCode: 200, body: '' }

  } catch (e) {
    console.error('[telegram-webhook]', e)
    return { statusCode: 200, body: '' }
  }
}
